name: Truncate Lists
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  sort:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          sudo apt install -y gawk

      - name: Sort list
        run: |
          # Sort all .list files in the additions directory
          find ${{ github.workspace }}/additions -type f -ipath '*temporary*' -exec truncate -s0 {} \;

          # Sort all .list files in the falsepositives directory
          find ${{ github.workspace }}/falsepositives -type f -ipath '*temporary*' -regextype posix-extended -iregex ".*\.(all|reg|rzdb)\.list" -exec awk -i inplace 'NR > 5 { next } { print }' {} \;
          find ${{ github.workspace }}/falsepositives -type f -ipath '*temporary*' -regextype posix-extended -not -iregex ".*\.(all|reg|rzdb)\.list" -exec truncate -s0 {} \;

      - name: Output changes
        run: git status

      - name: Push changes back to the repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -a -m "Truncate temporary lists" || echo "No changes to commit"
          git push
